@startuml
actor User as user
control "Upload\nsystem" as upload
control "Processing\nsystem" as processor
database Storage as storage
collections "Notification\nsystem" as notificator

user -> upload: Upload document
upload -> upload: check document structure

alt Successful case
    upload -> processor: Create processing task
    upload -> user: Show success message
else Error
    upload -> user: Show error message
end

... Background processing ...

processor -> processor: Process file

alt Successful case
    processor -> storage: Write data
    processor -> notificator: Send **success** message
else Error
    processor -> notificator: Send **error** message
end


@enduml